jwt:
    header: Authorization
    secret: mySecret
    expiration: 3600
    route:
      authentication:
        path: auth
        refresh: refresh



spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/test
    elasticsearch:
      cluster-name: wangxi's ES
      cluster-nodes: localhost:9300

  application:
    name: mongoweb
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
  http:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 100Mb
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1


  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
    timeout: 10

  jackson:
    serialization:
      INDENT_OUTPUT: true


#mysql 多数据 spring boot 2.x数据库配置
  datasource:
      old:
          url: jdbc:mysql://localhost:3306/FirstDataBase?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 123
          driver-class-name: com.mysql.jdbc.Driver
      new:
          url: jdbc:mysql://localhost:3306/SecondDataBase?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 123
          driver-class-name: com.mysql.jdbc.Driver

  jpa:
        properties:
          hibernate:
            show_sql: true
            format_sql: true
            ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          max-attempts: 5
          initial-interval: 3000
          enabled: true
        default-requeue-rejected: false
    virtual-host: wx


#端口配置
server:
  port: 8005

#配置日志
logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.mongodb.core: INFO
    org.springframework.data: INFO

  #自定义自动配置启动项目
wx-test:
  msg: 自定义自动配置项输出信息




